# Generated by Django 3.1.2 on 2020-11-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMascota', models.IntegerField(verbose_name='Id Mascota')),
                ('hora', models.DateTimeField(verbose_name='Hora vacuna')),
                ('fecha', models.DateField(verbose_name='Fecha vacuna')),
                ('laboratorio', models.CharField(max_length=50, verbose_name='nombre laboratorio')),
            ],
        ),
    ]
