# Generated by Django 3.1.2 on 2020-11-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='hora',
            field=models.TimeField(verbose_name='Hora vacuna'),
        ),
    ]
