# Generated by Django 3.1.2 on 2020-11-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre mascota')),
                ('fecha_nac', models.DateField(verbose_name='fecha nacimiento')),
                ('tipoMascota', models.CharField(max_length=50, verbose_name='tipo mascota')),
                ('tipoRaza', models.CharField(max_length=50, verbose_name='raza mascota')),
                ('dueño', models.CharField(max_length=50, verbose_name='rut dueño')),
            ],
        ),
        migrations.CreateModel(
            name='RazaMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion raza')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion del tipo')),
            ],
        ),
    ]
