# Generated by Django 3.1.2 on 2020-11-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default=None, upload_to='mascota', verbose_name='imagen mascota'),
        ),
    ]
