# Generated by Django 3.1.2 on 2020-11-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_auto_20201110_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nac',
            field=models.DateField(default=None, verbose_name='fecha nacimiento'),
        ),
    ]
