# Generated by Django 3.1.2 on 2020-11-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20201110_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nac',
            field=models.DateField(default=None, null=True, verbose_name='fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(null=True, upload_to='mascota', verbose_name='imagen mascota'),
        ),
    ]
