# Generated by Django 3.1.2 on 2020-11-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0007_auto_20201111_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='dueño',
            field=models.CharField(max_length=50, null=True, verbose_name='rut dueño'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(upload_to='mascotas', verbose_name='imagen mascota'),
        ),
    ]
